com-lihaoyi/cask

- docs/pages/1 - Cask: a Scala HTTP micro-framework.md
There were pair of really inconsequential typos in the documentation.
> Small typos

- build.sc
- cask/src/cask/endpoints/WebSocketEndpoint.scala
- cask/src/cask/main/Routes.scala
- cask/src/cask/package.scala
- cask/util/src-js/cask/util/Scheduler.scala
- cask/util/src-js/cask/util/WebsocketClientImpl.scala
- cask/util/src-jvm/cask/util/Scheduler.scala
- cask/util/src-jvm/cask/util/WebsocketClientImpl.scala
- cask/util/src/cask/util/BatchActor.scala
- cask/util/src/cask/util/Logger.scala
- cask/util/src/cask/util/WebsocketBase.scala
- cask/util/src/cask/util/Ws.scala
- cask/util/src/cask/util/WsClient.scala
- example/websockets/app/src/Websockets.scala
- example/websockets/app/test/src/ExampleTests.scala
- example/websockets2/app/test/src/ExampleTests.scala
Harmonize the actor-based APIs of `cask.WsClient`/`cask.WsHandler`/`cask.WsActor`, letting them share the same set of `cask.Ws` events
The default implementation of `cask.WsClient` on the JVM spawns one thread per connection, and doesn't really scale to large numbers of connections. For now we just continue using AsyncHttpClient in the load tests. Wrapping AsyncHttpClient in a nice API is TBD
> Provide a simple builtin websocket client in `cask.WsClient`

- cask/util/src-js/cask/util/WebsocketClientImpl.scala
- cask/util/src-jvm/cask/util/WebsocketClientImpl.scala
- cask/util/src/cask/util/WsClient.scala
- No more synchronous `.close` method; it has to go through `.send` like everyone else
- Check for a `closed` flag before calling `.close()` on the internal impl
> Tighten behavior of WebsocketClientImpl

- cask/src/cask/model/Params.scala
This adds the relatively new [SameSite option](https://www.owasp.org/index.php/SameSite) to cookies.
It simply forwards the [SameSite field from undertow](https://github.com/undertow-io/undertow/blob/ff4c9cf37872cb96070ba6a2fcbbaa6df291e390/core/src/main/java/io/undertow/server/handlers/CookieImpl.java#L166).
Modern browsers understand the values "Lax" and "Strict", so this field could also be exposed as an ADT. However, my preference would be to keep it as a string, since it allows future binary compatibility and also is the right abstraction IMO (anything beyond string in the HTTP world is assuming too much).
> Add SameSite option to cookies

- cask/src/cask/router/Macros.scala
- example/decorated/app/src/Decorated.scala
- example/decorated/app/test/src/ExampleTests.scala
In case of multiple parameter lists, the list index must also be taken into account.
> Fix index calculation of default parameters

- cask/src/cask/endpoints/WebEndpoints.scala
- cask/src/cask/main/Main.scala
- cask/src/cask/package.scala
- example/httpMethods/app/src/HttpMethods.scala
- example/httpMethods/app/test/src/ExampleTests.scala
This enables users to define custom HTTP methods in `cask.request` endpoints.
Previously, although that decorator allowed arbitrary methods, the dispatching triemap would only allow "get", "put", "post" and "websocket". This led to runtime errors when trying to access a "delete" endpoint, for example.
> Allow arbitrary HTTP methods

- build.sc
- cask/src/cask/main/Main.scala
- cask/src/cask/model/Params.scala
- example/cookies/app/src/Cookies.scala
- example/cookies/app/test/src/ExampleTests.scala
Commits are independent. Here' the gist:
---
- Undertow's cookie handling changed slightly in this version, which
prompted two changes:
1. the SameSite cookie no longer accepts null as an argument. Rather
than adding conditionals to guard setting, we simply change the
default SameSite value to 'Lax', as is assumed by modern standards
anyway https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite:
> The cookie-sending behavior if SameSite is not specified is SameSite=Lax.
> Previously the default was that cookies were sent for all requests.
2. it no longer handles spaces in cookie values (unless they are
quoted). This behavior is actually correct according to
[RFC2109](https://tools.ietf.org/html/rfc2109), which requires cookie
values to be quoted if they contain …
> Upgrade undertow and suppress startup messages

- cask/src/cask/main/Main.scala
- example/httpMethods/app/test/src/ExampleTests.scala
Currently, such methods lead to a match error in the routeTrie
lookup. This exception is printed, but since undertow defaults to
responding with 200, the effect is that requests with invalid methods
always return a successful response code.
The changes here modify this behavior to respond with a 405 if the
dispatch trie cannot be found in the method map.
> Reject requests with unsupported methods

- build.sc
to fix vulnerability https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11050
> Security issue: Update Java-WebSocket library to v.1.5.0

- cask/src/cask/internal/DispatchTrie.scala
- cask/src/cask/main/Main.scala
- cask/test/src/test/cask/DispatchTrieTests.scala
- example/variableRoutes/app/src/VariableRoutes.scala
- example/variableRoutes/app/test/src/ExampleTests.scala
This regressed in https://github.com/com-lihaoyi/cask/pull/52, resulting in both false positives (where a `GET` and a `POST` shared the same route, giving an unnecessary error) and false negatives (where multiple `GET`s sharing the same route failed to create an error). The basic problem was that since combining the various HTTP methods into a single routing trie, the old logic comparing uniqueness/duplication/etc. was no longer correct in the new combined trie.
This PR fixes it by doing a `groupBy` to split up the entries in the combined trie by HTTP method, before running essentially the same validation.
We augment the test suite, tightening up cask/test/src/test/cask/DispatchTrieTests.scala to make it stricter, checking exact error messages to ensure we get not just any failure but the …
> Fix DispatchTrie validation and reporting of invalid routes

- cask/src/cask/main/Main.scala
This PR modifies the "Upgrade" header check in `DefaultHandler.handleRequest` by using a case-insensitive comparison, as per the WebSocket RFC.
Sorry for the Yoda condition... it seems that Undertow's `HeaderMap.getFirst()` can return null.
Fixes #77
> Case-insensitive comparison of the "Upgrade" request header

- cask/src-3/cask/router/Macros.scala
- cask/src/cask/endpoints/WebEndpoints.scala
- cask/src/cask/model/Params.scala
- cask/src/cask/package.scala
- cask/src/cask/router/EntryPoint.scala
- cask/src/cask/router/Misc.scala
- docs/pages/1 - Cask: a Scala HTTP micro-framework.md
- example/variableRoutes/app/src/VariableRoutes.scala
- example/variableRoutes/app/test/src/ExampleTests.scala
Fixes https://github.com/com-lihaoyi/cask/issues/99
> Add `cask.QueryParams` type to allow route methods to take arbitrary query parameters

- cask/src/cask/endpoints/JsonEndpoint.scala
- cask/src/cask/endpoints/ParamReader.scala
- cask/src/cask/endpoints/WebEndpoints.scala
- cask/src/cask/main/Main.scala
- cask/src/cask/model/Params.scala
- cask/src/cask/package.scala
- cask/src/cask/router/Misc.scala
- docs/pages/1 - Cask: a Scala HTTP micro-framework.md
- example/formJsonPost/app/src/FormJsonPost.scala
- example/formJsonPost/app/test/src/ExampleTests.scala
- example/variableRoutes/app/src/VariableRoutes.scala
- example/variableRoutes/app/test/src/ExampleTests.scala
`subpath = true` as a named argument passed to the annotation runs into issues if multiple named arguments are present (see https://stackoverflow.com/questions/55032173/how-to-use-named-arguments-in-scala-user-defined-annotations), which prevents us from using named arguments to the annotation more broadly as a user-facing API. 
Using typed parameters to the method `def` sidesteps this issue, and neatly allows us to provide the captured value to the user. This is also more in line with how we handle inputs in general: cookies, known/typed query params, unknown query params, json input, form fields, etc.
> Make `cask.QueryParams` work for JSON endpoints, and form endpoints, replace `subpath = true` with `cask.RemainingPathSegments`

- docs/pages/1 - Cask: a Scala HTTP micro-framework.md
I've noticed that the badges could benefit from some polishing, as mentioned in #117.
1. The travis badge doesn't appear to work anymore.
2. I've noticed that the community is now on discord and that gitter has very low activity. 
I see that the #com-lihaoyi discord channel is pretty active.
I did manage to generate the docs using `./amm build.sc` with java 8, and here how the docs page looks now.
I could also update the README of the project with the badge to discord.
> Minor docs update. Update badges.

- example/decorated/app/src/Decorated.scala
- example/decorated/app/test/src/ExampleTests.scala
It would be helpful for the docs to show an example of a decorator returning a response. If there's a better way to do this then I'd be happy to make changes.
> Document decorator returning a response

- cask/src/cask/main/Main.scala
This allows customizing error responses based on data available in requests.
One scenario would be to display a 404, but with additional context information, e.g. the path or login status of the user taken from cookies.
> Pass request to error handlers

- cask/src/cask/internal/DispatchTrie.scala
- cask/src/cask/main/Main.scala
- cask/test/src/test/cask/DispatchTrieTests.scala
- example/queryParams/app/src/QueryParams.scala
- example/queryParams/app/test/src/ExampleTests.scala
This changes the DispatchTrie to allow overlapping wildcard segments in paths with static ones, with a preference for the latter.
For example, consider the following routes:
```
@cask.get("/settings")
def settings() = "settings"
@cask.get("/:id")
def user(id: String) = s"user $id"
```
This is currently not allowed. With these changes, it would be allowed, and the static route `settings` would be preferred, with a fallback to the dynamic route `user`:
```
GET /settings => settings
GET /foo => user foo
GET /bar => user bar
```
---
The reason I'm proposing this change is mostly for use in HTML applications (i.e. not RPC-style JSON APIs). In this scenario, short URLs are useful, since users may type them directly and associate meaning to them.
Consider for example the way GitHub structures …
> [RFC] Allow overlap between static routes and wildcards

- cask/src/cask/endpoints/FormEndpoint.scala
This makes it possible to parse non-ascii characters in form fields.
> Specify utf-8 as default form encoding in undertow helper

- cask/util/src/cask/util/Ws.scala
In undertow, the close codes 1002 and 1003 are swapped compared to the RFC. This mistake was copied into cask.
> Fix websocket close code constants

- build.mill
- cask/src-2/cask/main/Routes.scala
- cask/src-2/cask/router/Macros.scala
- cask/src-2/cask/router/RoutesEndpointMetadata.scala
- cask/src-3/cask/main/Routes.scala
- cask/src-3/cask/router/Macros.scala
- cask/src-3/cask/router/RoutesEndpointMetadata.scala
- cask/src/cask/decorators/compress.scala
- cask/src/cask/endpoints/FormEndpoint.scala
- cask/src/cask/endpoints/JsonEndpoint.scala
- cask/src/cask/endpoints/StaticEndpoints.scala
- cask/src/cask/endpoints/WebEndpoints.scala
- cask/src/cask/endpoints/WebSocketEndpoint.scala
- cask/src/cask/main/Main.scala
- cask/src/cask/router/Decorators.scala
- cask/src/cask/router/EndpointMetadata.scala
- cask/src/cask/router/EntryPoint.scala
- cask/test/src/test/cask/FailureTests.scala
- example/decorated/app/src/Decorated.scala
- example/decorated2/app/src/Decorated2.scala
- example/decoratedContext/app/src/DecoratedContext.scala
- example/decoratedContext/app/test/src/ExampleTests.scala
- example/decoratedContext/build.sc
- example/decoratedContext/package.mill
- example/endpoints/app/src/Endpoints.scala
- example/todo/app/src/TodoServer.scala
- example/todoDb/app/src/TodoMvcDb.scala
This allows customizing the way by-type parameters can be read: instead of always reading data from a `cask.Request`, this allows a decorator to parameterize the context type and pass it in explicitly from the `wrapFunction` method.
Essentially, this makes the context parameter of `ArgReader`s (which are used to translate data from a HTTP request to a scala parameter) customizable for every decorator.
The idea behind this proposal is to uniformize the way "named" and "by-type" parameters within the same endpoint are handled. By "named" parameters I mean parameters which are set from the `Map[String, Input]` in the delegate function, and by `by-type` parameters I mean parameters which are computed from an arity zero `ArgReader`, and thus use the `cask.Request` context to compute their …
> [RFC] Parameterize context type of decorators

- build.mill
- cask/src-3/cask/router/Macros.scala
- cask/test/src-3/test/cask/FailureTests3.scala
This includes more information in the error message that is generated when a route declaration has an invalid return type.
It notably also includes the source position, as discussed in #141.
> Rework compile time error message for scala 3

- cask/src/cask/main/Main.scala
- cask/src/cask/model/Params.scala
- cask/src/cask/router/Decorators.scala
This makes it possible to access raw path parameters in a decorator.
> Include bound path segments in request

- build.mill
- example/compress/package.mill
- example/compress2/package.mill
- example/compress3/package.mill
- example/cookies/package.mill
- example/decorated/package.mill
- example/decorated2/package.mill
- example/decoratedContext/package.mill
- example/endpoints/package.mill
- example/formJsonPost/package.mill
- example/httpMethods/package.mill
- example/minimalApplication/package.mill
- example/minimalApplication2/package.mill
- example/queryParams/package.mill
- example/redirectAbort/package.mill
- example/scalatags/package.mill
- example/staticFiles/package.mill
- example/staticFiles2/package.mill
- example/todo/package.mill
- example/todoApi/package.mill
- example/todoDb/package.mill
- example/twirl/package.mill
- example/variableRoutes/package.mill
- example/websockets/package.mill
- example/websockets2/package.mill
- example/websockets3/package.mill
- example/websockets4/package.mill
undertow to 2.3.18.Final
upickle to 4.0.2
requests to 0.9.0
sourcecode to 0.4.2
pprint to 0.9.0
geny to 1.1.1
utest to 0.8.4
> Upgrade various dependencies

- build.mill
- cask/src/cask/decorators/compress.scala
- example/compress/package.mill
- example/compress2/package.mill
- example/compress3/package.mill
- example/cookies/package.mill
- example/decorated/package.mill
- example/decorated2/package.mill
- example/decoratedContext/package.mill
- example/endpoints/package.mill
- example/formJsonPost/package.mill
- example/httpMethods/package.mill
- example/minimalApplication/package.mill
- example/minimalApplication2/package.mill
- example/queryParams/package.mill
- example/redirectAbort/package.mill
- example/scalatags/package.mill
- example/staticFiles/package.mill
- example/staticFiles2/package.mill
- example/todo/package.mill
- example/todoApi/package.mill
- example/todoDb/package.mill
- example/twirl/package.mill
- example/variableRoutes/package.mill
- example/websockets/package.mill
- example/websockets2/package.mill
- example/websockets3/package.mill
- example/websockets4/package.mill
Since we're compressing data on the fly, we can't know the content-length ahead of time. While requests 0.8.0 (which uses the JDK's URLConnection) allowed this, requests 0.9.0 (which uses the new HttpClient API) is stricter and fails.
Also upgrade requests to 0.9.0
> Drop content-length header in compressed decorator

- build.mill
- example/twirl/package.mill
It appears that it actually wasn't twirl that was preventing a build under jdk 21. Upgrading the various scala patch versions seems to fix it.
I've tested this manually on my machine. In the future, it could be interesting to also include a CI workflow that uses jdk 21.
Fixes #153
> Upgrade scala patch versions to support jdk 21

- cask/src/cask/endpoints/StaticEndpoints.scala
I discovered that there is a path traversal vulnerability with static files. Here is a [repository](https://github.com/Maeeen/cask-static-path-traversal-issue) that showcases the issue.
In `StaticUtil` (`StaticEndpoints.scala`), the `ctx.remainingPathSegments` is not properly sanitized and is priorly decoded in `Main.scala`. Therefore, if a static endpoint has a remaining path segment having `/` (e.g. if a client sends a `static/..%2F/hi.txt`), `filter` will fail to filter the `..` and the path `static/../hi.txt` will be returned to get returned to the client, which should be prohibited.
> Fix path traversal issue on static files

- build.mill
- cask/src/cask/model/Params.scala
- example/multipartFormSubmission/app/src/MultipartFormSubmission.scala
- example/multipartFormSubmission/app/test/src/ExampleTests.scala
- example/multipartFormSubmission/package.mill
Given a form with a file filed i.e. `<input type="file"/>` if the user does not include a file to upload when the form is submitted the browser will send a request with the following multipart body:
```
-----------------------------101075975012956453003083734809
Content-Disposition: form-data; name="some-field"
-----------------------------101075975012956453003083734809
Content-Disposition: form-data; name="a-file"; filename=""
Content-Type: application/octet-stream
-----------------------------101075975012956453003083734809--
```
Since there is no file but there is a file field, the browser will send a part with empty filename and body and octet-stream as the content type to signify a submission without a file to upload. 
In cask to handle such form submissions you create an endpoint …
> Fixes form submissions with empty file fields throwing exceptions

- .github/workflows/actions.yml
- build.mill
- cask/src/cask/internal/ThreadBlockingHandler.scala
- cask/src/cask/internal/Util.scala
- cask/src/cask/main/Main.scala
- docs/pages/1 - Cask - a Scala HTTP micro-framework.md
- example/minimalApplicationWithLoom/app/src/MinimalApplicationWithLoom.scala
- example/minimalApplicationWithLoom/app/test/src/ExampleTests.scala
- example/minimalApplicationWithLoom/package.mill
- example/staticFiles/package.mill
- example/staticFiles2/package.mill
- example/staticFilesWithLoom/app/resources/cask/example.txt
- example/staticFilesWithLoom/app/src/StaticFilesWithLoom.scala
- example/staticFilesWithLoom/app/test/src/ExampleTests.scala
- example/staticFilesWithLoom/package.mill
- example/todoDbWithLoom/app/src/TodoMvcDbWithLoom.scala
- example/todoDbWithLoom/app/test/src/ExampleTests.scala
- example/todoDbWithLoom/package.mill
Motivation:
Add Loom support.
refs: https://github.com/com-lihaoyi/cask/issues/90 , again 
Modification:
1. add `handlerExecutor()` and some helper methods for virtual threads.
2. some documents.
Result:
Virtual threads supported.
`wrk` is needed to run the benchmark
- miniAppWithSleep 100ms : ↑2300%
- todoDb:           ~↓6%
- staticFiles:      ~↓6%
```shell
./mill --no-build-lock benchmark.runBenchmarks
```
Results of same 4 Carrier/Platform threads:
```scala
[1] staticFilesWithLoom result with (platform threads):
[1] Running 30s test @ http://localhost:8080/
[1]   4 threads and 100 connections
[1]   Thread Stats   Avg      Stdev     Max   +/- Stdev
[1]     Latency     1.23ms  436.88us  28.64ms   98.91%
[1]     Req/Sec    20.54k     1.08k   22.69k    93.44%
[1]   2461250 requests in …
```
> feat: Add loom Support.

- docs/pages/1 - Cask - a Scala HTTP micro-framework.md
Motivation:
Update the doc, it's missing new line
@lihaoyi please add this and rererender the page
> chore: Add new line to the doc

- cask/src/cask/internal/Util.scala
- docs/pages/1 - Cask - a Scala HTTP micro-framework.md
Motivation: 
Add a helper method to create a separate virtual thread scheduler.
> chore: add a helper method to create a dedicated virtual thread scheduler.
